s12171934/trip-one-zido

trip-one-zido-api/src/main/java/com/example/triponezidoapi/controller/BookmarkApiController.java
trip-one-zido-api/src/main/java/com/example/triponezidoapi/controller/CommentApiController.java
trip-one-zido-api/src/main/java/com/example/triponezidoapi/controller/CommunityApiController.java
trip-one-zido-api/src/main/java/com/example/triponezidoapi/controller/ContentApiController.java
trip-one-zido-api/src/main/java/com/example/triponezidoapi/controller/MemberApiController.java
trip-one-zido-api/src/main/java/com/example/triponezidoapi/controller/PageApiController.java
trip-one-zido-api/src/main/java/com/example/triponezidoapi/controller/PlanApiController.java
trip-one-zido-api/src/main/java/com/example/triponezidoapi/controller/SpotApiController.java

REFACTOR: Controller parameter modified

---

trip-one-zido-api/src/main/resources/mappers/BookmarkMapper.xml
trip-one-zido-api/src/main/resources/mappers/CommunityMapper.xml
trip-one-zido-api/src/main/resources/mappers/ContentMapper.xml
trip-one-zido-api/src/main/resources/mappers/PlanMapper.xml
trip-one-zido-api/src/main/resources/mappers/SearchMapper.xml
trip-one-zido-api/src/main/resources/mappers/SpotMapper.xml
trip-one-zido-api/src/main/resources/mappers/TourMapper.xml

REFACTOR : list page nation

---

trip-one-zido-api/src/main/java/com/example/triponezidoapi/controller/BookmarkApiController.java
trip-one-zido-api/src/main/java/com/example/triponezidoapi/controller/PlanApiController.java
trip-one-zido-api/src/main/java/com/example/triponezidoapi/controller/SpotApiController.java
trip-one-zido-api/src/main/java/com/example/triponezidoapi/controller/TourApiController.java
trip-one-zido-api/src/main/java/com/example/triponezidoapi/service/BookmarkService.java
trip-one-zido-api/src/main/java/com/example/triponezidoapi/service/CommunityService.java
trip-one-zido-api/src/main/java/com/example/triponezidoapi/service/ContentService.java
trip-one-zido-api/src/main/java/com/example/triponezidoapi/service/MemberService.java
trip-one-zido-api/src/main/java/com/example/triponezidoapi/service/PlanService.java
trip-one-zido-api/src/main/java/com/example/triponezidoapi/service/SearchService.java
trip-one-zido-api/src/main/java/com/example/triponezidoapi/service/SpotService.java
trip-one-zido-api/src/main/java/com/example/triponezidoapi/service/TourService.java

REFACTOR: Service & Controller

---

trip-one-zido-api/src/main/java/com/example/triponezidoapi/dto/response/ResponseCommunity.java
trip-one-zido-api/src/main/java/com/example/triponezidoapi/service/CommunityService.java
trip-one-zido-api/src/main/java/com/example/triponezidoapi/service/PlanService.java
trip-one-zido-api/src/main/resources/mappers/CommunityMapper.xml

REFACTOR: own of owner rename

---

trip-one-zido-api/src/main/java/com/example/triponezidoapi/dto/response/ResponseSpotPlan.java
trip-one-zido-api/src/main/java/com/example/triponezidoapi/service/PlanService.java
trip-one-zido-api/src/main/resources/mappers/PlanMapper.xml

REFACTOR : ResponseSpotPlan dto change filedname  'start_date' > 'startDate'

FEAT : PlanService added returnObject and PlanMapper added column

---

trip-one-zido-api/src/main/java/com/example/triponezidoapi/service/PlanService.java

REFACTOR: PlanService

---

trip-one-zido-api/src/main/java/com/example/triponezidoapi/dto/response/ResponseSearch.java
trip-one-zido-api/src/main/java/com/example/triponezidoapi/service/SearchService.java
trip-one-zido-api/src/main/resources/mappers/SearchMapper.xml

- Response dto에서 안쓰이는 필드 제거(startDuration, endDuration)
* 사계절 기준 기간 검색 매퍼의 쿼리 수정 (detailSearchSpot, detailSearchPlan)

DOCS: Search

---

trip-one-zido-api/src/test/java/com/example/triponezidoapi/controller/CommunityApiControllerTest.java

TEST : CommunityApiControllerTest

---

trip-one-zido-api/src/main/java/com/example/triponezidoapi/dto/request/RequestPlan.java
trip-one-zido-api/src/main/java/com/example/triponezidoapi/dto/request/RequestSpot.java
trip-one-zido-api/src/main/java/com/example/triponezidoapi/dto/response/ResponseComment.java
trip-one-zido-api/src/main/java/com/example/triponezidoapi/dto/response/ResponsePhoto.java
trip-one-zido-api/src/main/java/com/example/triponezidoapi/dto/response/ResponsePlanDetail.java
trip-one-zido-api/src/main/java/com/example/triponezidoapi/dto/response/ResponseSpotDetail.java
trip-one-zido-api/src/main/java/com/example/triponezidoapi/dto/response/ResponseSpotPlan.java
trip-one-zido-api/src/main/java/com/example/triponezidoapi/service/PlanService.java
trip-one-zido-api/src/test/java/com/example/triponezidoapi/controller/BookmarkApiControllerTest.java
trip-one-zido-api/src/test/java/com/example/triponezidoapi/controller/PlanApiControllerTest.java
trip-one-zido-api/src/test/java/com/example/triponezidoapi/controller/SpotApiControllerTest.java

- Bookmark, Plan, Spot 테스트 코드에서 사용되는 DTO 생성자 삭제

REFACTOR: DTO

---

trip-one-zido-api/src/main/java/com/example/triponezidoapi/dto/Member.java
trip-one-zido-api/src/main/java/com/example/triponezidoapi/dto/response/ResponseBookmark.java
trip-one-zido-api/src/main/java/com/example/triponezidoapi/dto/response/ResponseContentList.java
trip-one-zido-api/src/main/java/com/example/triponezidoapi/dto/response/ResponseMemberPage.java
trip-one-zido-api/src/main/java/com/example/triponezidoapi/dto/response/ResponseSearch.java
trip-one-zido-api/src/main/java/com/example/triponezidoapi/mappers/MemberMapper.java
trip-one-zido-api/src/main/java/com/example/triponezidoapi/service/BookmarkService.java
trip-one-zido-api/src/main/java/com/example/triponezidoapi/service/PageService.java
trip-one-zido-api/src/main/resources/mappers/ContentMapper.xml
trip-one-zido-api/src/main/resources/mappers/MemberMapper.xml
trip-one-zido-api/src/test/java/com/example/triponezidoapi/controller/SearchApiControllerTest.java
trip-one-zido-vue/src/assets/zido.js
trip-one-zido-vue/src/components/member/Bookmark.vue
trip-one-zido-vue/src/components/member/MemberInfo.vue
trip-one-zido-vue/src/components/member/MemberPage.vue
trip-one-zido-vue/src/components/member/SignUp.vue

- 필드명 수정 (+4 squashed commit)
[5ca039e] REFACTOR : PageService modify
- setLoginId 매개변수 값 수정
[a12d21a] REFACTOR: ResponseSearch DTO field add
- 검색된 계정, 일정, 장소 개수 추가
- 테스트 코드에 추가 후 검증 확인
[4de6d9a] REFACTOR: componets/member refactor
- 비교 후 DTO, mapper 수정
[3b0798f] FEAT: Bookmark, Community js axios add

REFACTOR : member DTO modify

---

trip-one-zido-api/src/main/java/com/example/triponezidoapi/controller/ContentApiController.java
trip-one-zido-api/src/main/java/com/example/triponezidoapi/controller/PageApiController.java
trip-one-zido-api/src/main/java/com/example/triponezidoapi/dto/response/ResponsePlanDetail.java
trip-one-zido-api/src/main/java/com/example/triponezidoapi/service/ContentService.java
trip-one-zido-api/src/main/java/com/example/triponezidoapi/service/PageService.java
trip-one-zido-api/src/main/resources/mappers/ContentMapper.xml
trip-one-zido-api/src/main/resources/mappers/MemberMapper.xml
trip-one-zido-api/src/test/java/com/example/triponezidoapi/controller/ContentApiControllerTest.java
trip-one-zido-api/src/test/java/com/example/triponezidoapi/controller/PageApiControllerTest.java
trip-one-zido-vue/src/assets/zido.js
trip-one-zido-vue/src/components/plan/EditPlan.vue
trip-one-zido-vue/src/components/plan/PlanDetail.vue

[116e6a0] FEAT: Content, Comment, Follow, Good  axios add
[6164c24] REFACTOR : Controller and Service refactor

REFACOTR : Plan vue refactor (+2 squashed commit)

---

.idea/misc.xml
trip-one-zido-api/src/main/java/com/example/triponezidoapi/controller/MemberApiController.java
trip-one-zido-api/src/main/java/com/example/triponezidoapi/mappers/MemberMapper.java
trip-one-zido-api/src/main/java/com/example/triponezidoapi/service/MemberService.java
trip-one-zido-api/src/main/resources/mappers/MemberMapper.xml
trip-one-zido-api/src/test/java/com/example/triponezidoapi/controller/MemberApiControllerTest.java
trip-one-zido-vue/src/assets/zido.js

[947bc03] REFACTOR : Member - Controller and Service and Mapper refactor

FEAT: Member(1)  axios add (+1 squashed commits)

---

trip-one-zido-api/src/main/java/com/example/triponezidoapi/controller/MemberApiController.java
trip-one-zido-api/src/main/java/com/example/triponezidoapi/dto/response/ResponseConfigPage.java
trip-one-zido-api/src/main/java/com/example/triponezidoapi/service/MemberService.java
trip-one-zido-vue/src/assets/data.js
trip-one-zido-vue/src/assets/zido.js
trip-one-zido-vue/src/assets/zido_2.js

[6743362] Feature : add dto, controller, service (config page)
[b21d9ca] Refactor : setting axios of member (zido.js)

Refactor : zido.js (comment processing -> login) (+2 squashed commit)

---

trip-one-zido-api/src/main/java/com/example/triponezidoapi/controller/MemberApiController.java
trip-one-zido-api/src/main/java/com/example/triponezidoapi/dto/request/RequestCommunity.java
trip-one-zido-api/src/main/java/com/example/triponezidoapi/service/CommentService.java
trip-one-zido-api/src/main/java/com/example/triponezidoapi/service/MemberService.java
trip-one-zido-api/src/main/resources/mappers/MemberMapper.xml
trip-one-zido-api/src/test/java/com/example/triponezidoapi/controller/MemberApiControllerTest.java

- 아이디 중복 시 오류 메시지 발생하도록 수정
- member DTO 에서 question -> questionId 수정에 따른 mapper 수정 (+4 squashed commit)
[36dc0d3] REFACOTR :  Member Controller remove pairingSignup
[bb34916] REFACTOR: RequestCommunity
- status valid 수정
[d5374e6] REFACTOR : Comment
[f3ed777] REFACTOR : member field modify
- question -> questionId

REFACTOR : member service & mapper

---

trip-one-zido-api/src/main/java/com/example/triponezidoapi/controller/ContentApiController.java
trip-one-zido-api/src/main/java/com/example/triponezidoapi/dto/Member.java
trip-one-zido-api/src/main/java/com/example/triponezidoapi/service/MemberService.java
trip-one-zido-api/src/main/java/com/example/triponezidoapi/service/SearchService.java
trip-one-zido-api/src/main/resources/mappers/MemberMapper.xml
trip-one-zido-vue/src/assets/data.js
trip-one-zido-vue/src/assets/zido.js
trip-one-zido-vue/src/components/member/Find.vue
trip-one-zido-vue/src/components/member/SignUp.vue
trip-one-zido-vue/src/components/util/modal/SecurityModal.vue

[72ce90c] IMPROVE : signup code improve
[496fc15] IMPROVE : singup code improve
[2987b35] REFACOTR : Find.vue code refactor
[c25688d] REFACOTR : vue code refactor
[2f82e87] REFACOTR : count logic added

REFACOTR : value change '0' -> '남' (+5 squashed commit)

---

trip-one-zido-api/src/main/java/com/example/triponezidoapi/controller/MemberApiController.java
trip-one-zido-api/src/main/java/com/example/triponezidoapi/dto/Member.java
trip-one-zido-api/src/main/java/com/example/triponezidoapi/dto/response/ResponseSearch.java
trip-one-zido-api/src/main/java/com/example/triponezidoapi/service/MemberService.java
trip-one-zido-api/src/main/resources/mappers/MemberMapper.xml
trip-one-zido-api/src/main/resources/mappers/SpotMapper.xml
trip-one-zido-api/src/test/java/com/example/triponezidoapi/controller/MemberApiControllerTest.java
trip-one-zido-vue/src/assets/zido.js
trip-one-zido-vue/src/components/member/MemberInfo.vue
trip-one-zido-vue/src/components/member/ResetPassword.vue
trip-one-zido-vue/src/components/member/Resign.vue

- 회원탈퇴, 비밀번호 변경 페이지/모달 이동 오류 수정 (+6 squashed commit)
[2d65cbe] REFACTOR : Resign
- 회원탈퇴 기능 오류 수정
- mapper parameterType long -> Long, 쿼리 오류 수정
- zido.js checkResign axios url 수정
[e3309db] REFACTOR : zido.js
[c1528be] REFACTOR : Member 비밀번호 변경
[a0804b7] REFACTOR : Member 회원정보조회, 수정
+ 우편번호, 상세주소 컬럼 추가
[215d759] REFACTOR : Member field name modify
questionId -> question
[0268d49] REFACTOR :  Spot mapper, ResponseSearch
- spot 매퍼 쿼리 수정
- response search dto 수정

REFACTOR : Member Resign, ResetPassword

---

.gitignore
package-lock.json
package.json
trip-one-zido-vue/src/components/community/Community.vue
trip-one-zido-vue/src/components/community/CommunityDetail.vue
trip-one-zido-vue/src/components/community/EditCommunity.vue
trip-one-zido-vue/src/components/member/Config.vue
trip-one-zido-vue/src/components/member/Find.vue
trip-one-zido-vue/src/components/member/Login.vue
trip-one-zido-vue/src/components/member/MemberPage.vue

CommunityDetailm,EditCommunity 모집중,목록,이전글,다음글 버튼 한줄로 만들기 / 칸마다 아랫줄 생성 EditCommunity 등록,수정버튼 수정
Config 프로필사진 px -> %로 변경
Find 프로필사진 width만 px -> %로 변경
Login 체크박스부분 -2md 설정 뺌
MemberPage 프로필사진 px -> %로 변경

Docs : Community deadLine->deadline / 등록버튼수정

---

trip-one-zido-api/src/main/resources/mappers/BookmarkMapper.xml
trip-one-zido-api/src/main/resources/mappers/ContentMapper.xml
trip-one-zido-api/src/main/resources/mappers/PlanMapper.xml
trip-one-zido-api/src/main/resources/mappers/SearchMapper.xml
trip-one-zido-api/src/main/resources/mappers/SpotMapper.xml

[fea300d] FIX : 공개/비공개에 따른 게시글 조회 수정

REFACTOR : 공개/비공개에 따른 게시글 조회 수정 (+1 squashed commits)

---

trip-one-zido-api/src/main/java/com/example/triponezidoapi/dto/response/ResponseSpotPlan.java
trip-one-zido-api/src/main/java/com/example/triponezidoapi/service/PlanService.java
trip-one-zido-api/src/main/resources/mappers/PlanMapper.xml
trip-one-zido-api/src/main/resources/mappers/SpotMapper.xml

[871f347] FIX : Spot테이블 컬럼 추가에 맞추어 DTO,Mapper 수정

FIX : spot title update code added (+1 squashed commits)

---

trip-one-zido-api/src/main/java/com/example/triponezidoapi/dto/response/ResponseSearch.java
trip-one-zido-api/src/main/java/com/example/triponezidoapi/mappers/SearchMapper.java
trip-one-zido-api/src/main/java/com/example/triponezidoapi/service/SearchService.java
trip-one-zido-api/src/main/resources/mappers/SearchMapper.xml
trip-one-zido-vue/src/assets/data.js
trip-one-zido-vue/src/assets/zido.js
trip-one-zido-vue/src/components/search/DetailSearch.vue
trip-one-zido-vue/src/components/search/Search.vue
trip-one-zido-vue/src/components/spot/EditSpot.vue

[d0b45cd] REFACTOR: detailSearch
[d64fe9c] FEAT & REFACTOR : searchDetail
- countDetail 추가
- 기간 검색 -> 계절 카테고리로 변경

REFACTOR : newContents (+2 squashed commit)

---

trip-one-zido-vue/src/assets/data.js
trip-one-zido-vue/src/assets/zido.js
trip-one-zido-vue/src/components/member/Config.vue
trip-one-zido-vue/src/components/member/Login.vue
trip-one-zido-vue/src/components/util/NumberSummary.vue

[6c02c3c] FIX : dataField name change
[0f5bc76] REFACOTR : config.vue code refactor

FIX : login modal fix (+2 squashed commit)

---

trip-one-zido-vue/src/components/plan/EditPlan.vue
trip-one-zido-vue/src/components/plan/PlanDetail.vue
trip-one-zido-vue/src/components/search/DetailSearch.vue
trip-one-zido-vue/src/components/search/Search.vue
trip-one-zido-vue/src/components/spot/EditSpot.vue
trip-one-zido-vue/src/components/spot/Map.vue
trip-one-zido-vue/src/components/spot/SpotDetail.vue
trip-one-zido-vue/src/components/tour/TourDetail.vue
trip-one-zido-vue/src/components/tour/TourPage.vue

[2144a9a] REFACTOR : Vue
- plan, search, spot, tour

REFACTOR : vue

---

trip-one-zido-api/src/main/java/com/example/triponezidoapi/dto/request/RequestPlan.java
trip-one-zido-api/src/main/java/com/example/triponezidoapi/plan/PlanApiController.java
trip-one-zido-api/src/main/java/com/example/triponezidoapi/plan/PlanService.java
trip-one-zido-vue/src/components/plan/EditPlan.vue

[1dc0593] FIX : Editplan spot update code fix

FIX : Editplan code fix (+1 squashed commits)
